PRODUCER_KEY = 'producer'
PRODUCER_NAME = 'ymir'
EXECUTOR_CONFIG_KEY = 'executor_config'
TASK_CONTEXT_KEY = 'task_context'
TASK_CONTEXT_PREPROCESS_KEY = 'preprocess'
EXECUTOR_OUTLOG_NAME = 'ymir-executor-out.log'
COCO_JSON_NAME = 'coco-annotations.json'

BYTES_PER_MB = 1048576
ASSET_LIMIT_PER_DATASET = 1000000

# evaluate default args
DEFAULT_EVALUATE_CONF_THR = 0.005
DEFAULT_EVALUATE_IOU_THR = '0.5'
DEFAULT_EVALUATE_SUB_CKS = 10

# evaluation limitations
MAX_EVALUATION_ASSETS_COUNT = 50000
MAX_EVALUATION_CLASS_IDS_COUNT = 20
