PRODUCER_KEY = 'producer'
PRODUCER_NAME = 'ymir'
EXECUTOR_CONFIG_KEY = 'executor_config'
TASK_CONTEXT_KEY = 'task_context'
TASK_CONTEXT_PARAMETERS_KEY = 'task_parameters'
TASK_CONTEXT_PREPROCESS_KEY = 'preprocess'
EXECUTOR_OUTLOG_NAME = 'ymir-executor-out.log'

BYTES_PER_MB = 1048576
ASSET_LIMIT_PER_DATASET = 1000000

# about evaluate default args
DEFAULT_EVALUATE_CONF_THR = 0.005
DEFAULT_EVALUATE_IOU_THR = '0.5'
DEFAULT_EVALUATE_SUB_CKS = 10
