version: '3.3'
services:
  51plugin_app:
    image: ymir_plugin/fiftyone
    env_file:
      - .env
    environment:
      FIFTYONE_DATABASE_URI: "mongodb://51plugin_mongo:27017"
      FIFTYONE_REDIS_HOST: "51plugin_redis"
    volumes:
      - ${BACKEND_SANDBOX_ROOT}:${BACKEND_SANDBOX_ROOT}
    ports:
      - "5151:5151"
    restart: always
    networks:
      - 51pluginnetwork
    depends_on:
      - 51plugin_mongo

  51plugin_worker:
    image: ymir_plugin/51api:v1
    env_file:
      - .env
    environment:
      FIFTYONE_DATABASE_URI: "mongodb://51plugin_mongo:27017"
      FIFTYONE_REDIS_HOST: "51plugin_redis"
      FIFTYONE_BASE_PATH: ${BACKEND_SANDBOX_ROOT}
    volumes:
      - ${BACKEND_SANDBOX_ROOT}:${BACKEND_SANDBOX_ROOT}
    command: "celery -A app.main.celery worker --loglevel=INFO"
    restart: always
    networks:
      - 51pluginnetwork
    depends_on:
      - 51plugin_mongo

  51plugin_web:
    image: ymir_plugin/fiftyone_web:v1
    restart: always
    ports:
      - "8082:80"
    networks:
      - 51pluginnetwork
    depends_on:
      - 51plugin_mongo

  51plugin_backend:
    image: ymir_plugin/51api:v1
    env_file:
      - .env
    environment:
      FIFTYONE_DATABASE_URI: "mongodb://51plugin_mongo:27017"
      FIFTYONE_REDIS_HOST: "51plugin_redis"
      FIFTYONE_BASE_PATH: ${BACKEND_SANDBOX_ROOT}
    volumes:
      - ${BACKEND_SANDBOX_ROOT}:${BACKEND_SANDBOX_ROOT}
    ports:
      - "8080:8080"
    restart: always
    networks:
      - 51pluginnetwork
    depends_on:
      - 51plugin_mongo

  51plugin_redis:
    image: redis:5.0.4
    command: redis-server --appendonly yes
    volumes:
      - ${YMIR_PATH}/51plugin/redis-data:/data
    networks:
      - 51pluginnetwork
    restart: always

  51plugin_mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    restart: always
    networks:
      - 51pluginnetwork

networks:
  51pluginnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.68.254.0/24
          gateway: 172.68.254.1
