# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import backend_pb2 as backend__pb2


class mir_controller_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.data_manage_request = channel.unary_unary(
                '/ymir.backend.mir_controller_service/data_manage_request',
                request_serializer=backend__pb2.GeneralReq.SerializeToString,
                response_deserializer=backend__pb2.GeneralResp.FromString,
                )


class mir_controller_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def data_manage_request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_mir_controller_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'data_manage_request': grpc.unary_unary_rpc_method_handler(
                    servicer.data_manage_request,
                    request_deserializer=backend__pb2.GeneralReq.FromString,
                    response_serializer=backend__pb2.GeneralResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ymir.backend.mir_controller_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class mir_controller_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def data_manage_request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ymir.backend.mir_controller_service/data_manage_request',
            backend__pb2.GeneralReq.SerializeToString,
            backend__pb2.GeneralResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class hel_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.hel_ops_process = channel.unary_unary(
                '/ymir.backend.hel_service/hel_ops_process',
                request_serializer=backend__pb2.HelOpsRequest.SerializeToString,
                response_deserializer=backend__pb2.HelOpsResponse.FromString,
                )


class hel_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def hel_ops_process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_hel_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'hel_ops_process': grpc.unary_unary_rpc_method_handler(
                    servicer.hel_ops_process,
                    request_deserializer=backend__pb2.HelOpsRequest.FromString,
                    response_serializer=backend__pb2.HelOpsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ymir.backend.hel_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class hel_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def hel_ops_process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ymir.backend.hel_service/hel_ops_process',
            backend__pb2.HelOpsRequest.SerializeToString,
            backend__pb2.HelOpsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
