{
 "title": "Docker Containers",
 "description": "Containers metrics",
 "tags": [ "docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "filename", "label": "Filename", "query": "label_values(filename)" },
   { "name": "search", "label": "String Match" }
  ]
 },
 "panels": [
  { "title": "YMIR-logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"$filename\"} |= \"$search\" [$__interval]))"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{filename=\"$filename\"} |= \"$search\""
    }
   ]
  },
  {
   "title": "YMIR-Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Health Rate (last 15m)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_compose_service=\"web\"}[15m]))",
     "legendFormat": "web"
    },
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_compose_service=\"backend\"}[15m]))",
     "legendFormat": "backend"
    },
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_compose_service=\"db\"}[15m]))",
     "legendFormat": "db"
    },
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_compose_service=\"mongodb\"}[15m]))",
     "legendFormat": "mongodb"
    },
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_compose_service=\"redis\"}[15m]))",
     "legendFormat": "redis"
    },
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_compose_service=\"tensorboard\"}[15m]))",
     "legendFormat": "tensorboard"
    },
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_compose_service=\"labelstudio\"}[15m]))",
     "legendFormat": "labelstudio"
    },
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_compose_service=\"blackbox\"}[15m]))",
     "legendFormat": "blackbox"
    },
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_compose_service=\"cadvisor\"}[15m]))",
     "legendFormat": "cadvisor"
    },
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_compose_service=\"grafana\"}[15m]))",
     "legendFormat": "grafana"
    },
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_compose_service=\"nodeexporter\"}[15m]))",
     "legendFormat": "nodeexporter"
    },
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_compose_service=\"prometheus\"}[15m]))",
     "legendFormat": "prometheus"
    },
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_compose_service=\"loki\"}[15m]))",
     "legendFormat": "loki"
    },
    {
     "expr": "sum(rate(container_last_seen{container_label_com_docker_compose_service=\"promtail\"}[15m]))",
     "legendFormat": "promtail"
    }
   ]
  },
  {
   "title": "Core Service Alert",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "absent(container_last_seen{container_label_com_docker_compose_service=\"web\"})",
     "legendFormat": "web"
    },
    {
     "expr": "absent(container_last_seen{container_label_com_docker_compose_service=\"backend\"})",
     "legendFormat": "backend"
    },
    {
     "expr": "absent(container_last_seen{container_label_com_docker_compose_service=\"db\"})",
     "legendFormat": "db"
    },
    {
     "expr": "absent(container_last_seen{container_label_com_docker_compose_service=\"mongodb\"})",
     "legendFormat": "mongodb"
    },
    {
     "expr": "absent(container_last_seen{container_label_com_docker_compose_service=\"redis\"})",
     "legendFormat": "redis"
    },
    {
     "expr": "absent(container_last_seen{container_label_com_docker_compose_service=\"tensorboard\"})",
     "legendFormat": "tensorboard"
    },
    {
     "expr": "absent(container_last_seen{container_label_com_docker_compose_service=\"labelstudio\"})",
     "legendFormat": "labelstudio"
    }
   ]
  },
  {
   "title": "YMIR-App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "App-Requests",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_code, path, job) (starlette_requests_total)",
     "legendFormat": "{{job}}-{{path}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(starlette_request_duration_seconds_bucket[5m])) by (le, instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(starlette_request_duration_seconds_bucket[5m])) by (le, instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum (starlette_request_duration_seconds_count) / sum(starlette_request_duration_seconds_sum)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Slow Response",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum (rate(starlette_request_duration_seconds_bucket[5m])) by (le, instance, path, status_code))",
     "legendFormat": "{{ instance }}-{{path}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "YMIR-Viewer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Viewer-Requests",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code, uri, instance) (gin_uri_request_total)",
     "legendFormat": "{{instance}}-{{uri}}-{{code}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(gin_request_duration_bucket[5m])) by (le, instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(gin_request_duration_bucket[5m])) by (le, instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum (gin_request_duration_sum) / sum(gin_request_duration_count)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Slow Request(> 10s)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(uri, instance) (gin_slow_request_total)",
     "legendFormat": "{{instance}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m])) / count(node_cpu_seconds_total{mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Memory Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Storage Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype=~\"aufs|ext4\"} - node_filesystem_free_bytes{fstype=~\"aufs|ext4\"}) / node_filesystem_size_bytes{fstype=~\"aufs|ext4\"}  * 100"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(container_fs_usage_bytes)" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Cached Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_memory_cache{image!=\"\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[5m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[5m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}