"""rename training_type to object_type in project table

Revision ID: 15d9d969db46
Revises: 239ad4896058
Create Date: 2022-11-30 16:13:18.487545

"""
from alembic import op

# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "15d9d969db46"
down_revision = "239ad4896058"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("project", "ix_project_training_type")
    op.alter_column("project", "training_type", new_column_name="object_type")
    op.create_index("project", "ix_project_object_type")


#   with op.batch_alter_table('project', schema=None) as batch_op:
#       batch_op.add_column(sa.Column('object_type', sa.SmallInteger(), nullable=False))
#       batch_op.drop_index('ix_project_training_type')
#       batch_op.create_index(batch_op.f('ix_project_object_type'), ['object_type'], unique=False)
#       batch_op.drop_column('training_type')

# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("project", "ix_project_object_type")
    op.alter_column("project", "object_type", new_column_name="training_type")
    op.create_index("project", "ix_project_training_type")


#   with op.batch_alter_table('project', schema=None) as batch_op:
#       batch_op.add_column(sa.Column('training_type', sa.SMALLINT(), nullable=False))
#       batch_op.drop_index(batch_op.f('ix_project_object_type'))
#       batch_op.create_index('ix_project_training_type', ['training_type'], unique=False)
#       batch_op.drop_column('object_type')

# ### end Alembic commands ###
