"""add enable_livecode to docker_image tbl

Revision ID: 501414124392
Revises: e2fe87f35cf4
Create Date: 2022-06-24 23:20:12.442721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501414124392'
down_revision = 'e2fe87f35cf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docker_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column("enable_livecode", sa.Boolean(), nullable=False, server_default="0"))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index('ix_project_testing_dataset_id')
        batch_op.create_index(batch_op.f('ix_project_validation_dataset_id'), ['validation_dataset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_validation_dataset_id'))
        batch_op.create_index('ix_project_testing_dataset_id', ['validation_dataset_id'], unique=False)

    with op.batch_alter_table('docker_image', schema=None) as batch_op:
        batch_op.drop_column('enable_livecode')

    # ### end Alembic commands ###
