"""add mask_ap in model table

Revision ID: 5c8cc5112b38
Revises: 239ad4896058
Create Date: 2023-01-10 15:12:51.753119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c8cc5112b38"
down_revision = "239ad4896058"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mask_ap", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model", schema=None) as batch_op:
        batch_op.drop_column("mask_ap")
    # ### end Alembic commands ###
