"""add keywords to model tbl

Revision ID: a5b7b9a297b2
Revises: e2503210ac29
Create Date: 2022-07-21 10:27:11.780720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a5b7b9a297b2"
down_revision = "e2503210ac29"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model", schema=None) as batch_op:
        batch_op.add_column(sa.Column("keywords", sa.Text(length=20000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model", schema=None) as batch_op:
        batch_op.drop_column("keywords")
    # ### end Alembic commands ###
