"""is_sample_prj

Revision ID: db601aacf6d8
Revises: e429a1fd8c61
Create Date: 2022-04-19 10:56:19.104072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "db601aacf6d8"
down_revision = "e429a1fd8c61"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_sample", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.drop_column("is_sample")

    # ### end Alembic commands ###
