"""update project

Revision ID: e2fe87f35cf4
Revises: 0a65ca497350
Create Date: 2022-06-20 15:38:05.416763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fe87f35cf4'
down_revision = '0a65ca497350'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('iteration', 'testing_dataset_id', new_column_name='validation_dataset_id', existing_type=sa.Integer())

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testing_dataset_ids', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('enable_iteration', sa.Boolean(), nullable=False, default=True, server_default='1'))
    op.alter_column('project', 'testing_dataset_id', new_column_name='validation_dataset_id', existing_type=sa.Integer())

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('enable_iteration')
        batch_op.drop_column('testing_dataset_ids')
    op.alter_column('project', 'validation_dataset_id', new_column_name='testing_dataset_id', existing_type=sa.Integer())

    op.alter_column('iteration', 'validation_dataset_id', new_column_name='testing_dataset_id', existing_type=sa.Integer())

    # ### end Alembic commands ###
