"""update_051

Revision ID: fce82874b5fb
Revises: f05268b15d34
Create Date: 2022-04-18 11:09:52.304276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fce82874b5fb"
down_revision = "f05268b15d34"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dataset", "is_protected")
    op.add_column("project", sa.Column("initial_training_dataset_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_project_initial_training_dataset_id"), "project", ["initial_training_dataset_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_initial_training_dataset_id"), table_name="project")
    op.drop_column("project", "initial_training_dataset_id")
    op.add_column("dataset", sa.Column("is_protected", sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
