"""update tbl: user has state

Revision ID: 2073e21f39cf
Revises: 2c9f9be88430
Create Date: 2021-12-15 09:28:25.026607

"""
import sqlalchemy as sa

from alembic import context, op

# revision identifiers, used by Alembic.
revision = "2073e21f39cf"
down_revision = "2c9f9be88430"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if context.get_x_argument(as_dictionary=True).get("sqlite", None):
        with op.batch_alter_table("user") as batch_op:
            batch_op.add_column(sa.Column("state", sa.Integer(), nullable=True))
            batch_op.create_index(op.f("ix_user_state"), ["state"], unique=False)
            batch_op.add_column(sa.Column("role", sa.Integer(), nullable=True))
            batch_op.create_index(op.f("ix_user_role"), ["role"], unique=False)
            batch_op.drop_column("is_admin")
    else:
        op.add_column("user", sa.Column("state", sa.Integer(), nullable=True))
        op.create_index(op.f("ix_user_state"), "user", ["state"], unique=False)
        op.add_column("user", sa.Column("role", sa.Integer(), nullable=True))
        op.create_index(op.f("ix_user_role"), "user", ["role"], unique=False)
        op.drop_column("user", "is_admin")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if context.get_x_argument(as_dictionary=True).get("sqlite", None):
        with op.batch_alter_table("user") as batch_op:
            batch_op.add_column(sa.Column("is_admin", sa.BOOLEAN(), nullable=True))
            batch_op.drop_index(op.f("ix_user_state"))
            batch_op.drop_column("state")
            batch_op.drop_index(op.f("ix_user_role"))
            batch_op.drop_column("role")
    else:
        op.add_column("user", sa.Column("is_admin", sa.BOOLEAN(), nullable=True))
        op.drop_index(op.f("ix_user_state"), table_name="user")
        op.drop_column("user", "state")
        op.drop_index(op.f("ix_user_role"), table_name="role")
        op.drop_column("user", "role")
    # ### end Alembic commands ###
