"""update uniq constraint

Revision ID: 5068aee30aed
Revises: 7815c78f3469
Create Date: 2021-10-19 10:28:25.713782

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5068aee30aed"
down_revision = "7815c78f3469"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_dataset_userid_name", table_name="dataset")
    op.drop_index("ix_model_name", table_name="model")
    op.create_index(op.f("ix_model_name"), "model", ["name"], unique=False)
    op.drop_index("ix_user_username", table_name="user")
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_index("ix_user_username", "user", ["username"], unique=False)
    op.drop_index(op.f("ix_model_name"), table_name="model")
    op.create_index("ix_model_name", "model", ["name"], unique=False)
    op.create_index(
        "ix_dataset_userid_name", "dataset", ["user_id", "name"], unique=False
    )
    # ### end Alembic commands ###
