"""new table: docker_image_relationship

Revision ID: 64baca4a2ebe
Revises: 8f18096e2db7
Create Date: 2021-12-20 11:38:34.230175

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "64baca4a2ebe"
down_revision = "8f18096e2db7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "docker_image_relationship",
        sa.Column("src_image_id", sa.Integer(), nullable=False),
        sa.Column("dest_image_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("src_image_id", "dest_image_id"),
        sa.UniqueConstraint(
            "src_image_id", "dest_image_id", name="unique_image_relationship"
        ),
    )
    op.create_index(
        op.f("ix_docker_image_relationship_dest_image_id"),
        "docker_image_relationship",
        ["dest_image_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_docker_image_relationship_src_image_id"),
        "docker_image_relationship",
        ["src_image_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_docker_image_relationship_src_image_id"),
        table_name="docker_image_relationship",
    )
    op.drop_index(
        op.f("ix_docker_image_relationship_dest_image_id"),
        table_name="docker_image_relationship",
    )
    op.drop_table("docker_image_relationship")
    # ### end Alembic commands ###
