"""add config to task tbl

Revision ID: 7815c78f3469
Revises: 3bfb2b0e287d
Create Date: 2021-10-11 15:19:26.287832

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7815c78f3469"
down_revision = "3bfb2b0e287d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runtime",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("hash", sa.String(length=50), nullable=True),
        sa.Column(
            "type",
            sa.Enum("unknown", "training", "mining", "inference", name="runtimetype"),
            nullable=True,
        ),
        sa.Column("config", sa.String(length=500), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("create_datetime", sa.DateTime(), nullable=False),
        sa.Column("update_datetime", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runtime_hash"), "runtime", ["hash"], unique=False)
    op.create_index(op.f("ix_runtime_id"), "runtime", ["id"], unique=False)
    op.create_index(op.f("ix_runtime_name"), "runtime", ["name"], unique=False)
    op.create_index(op.f("ix_runtime_type"), "runtime", ["type"], unique=False)
    op.add_column("task", sa.Column("config", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "config")
    op.drop_index(op.f("ix_runtime_type"), table_name="runtime")
    op.drop_index(op.f("ix_runtime_name"), table_name="runtime")
    op.drop_index(op.f("ix_runtime_id"), table_name="runtime")
    op.drop_index(op.f("ix_runtime_hash"), table_name="runtime")
    op.drop_table("runtime")
    # ### end Alembic commands ###
