YmirSandbox: ""

ViewerHost: "0.0.0.0"
ViewerPort: 9527
# ViewerURI has higher priority than above fields, if set.
ViewerURI: ""

MongoDBURI: "mongodb://127.0.0.1:27017"
MongoDBName: "YMIR"
MongoDBNoCache: true

InnerTimeout: 10
