YmirSandbox: ""

ViewerHost: "127.0.0.1"
ViewerPort: 9527
# ViewerURI has higher priority than above fields, if set.
ViewerURI: ""

MongoDBURI: "mongodb://127.0.0.1:27017"
MongoDataDBName: "YMIR-data"
MongoDataDBCache: true

InnerTimeout: 61 # +1 for elder.
