FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y git \
  && apt-get install -y --no-install-recommends python3-pip python3-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

RUN pip install --no-cache-dir "uvicorn[standard]" --index-url=https://mirrors.aliyun.com/pypi/simple gunicorn

RUN mkdir -p /data/sharing/
RUN mkdir -p /app_logs/

COPY requirements.txt ./
RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

RUN pip3 uninstall -y ymir-cmd
RUN pip3 install --force-reinstall -U "git+https://github.com/IndustryEssentials/ymir.git/@dev#egg=ymir-cmd&subdirectory=ymir/command"

COPY ./src /app
WORKDIR /app

COPY ./deploy/git.config /root/.gitconfig


COPY ./deploy/supervisor /app/supervisor

ENV PYTHONPATH=/app/pymir-app:/app/pymir-controller:/app/pymir-viz:/app/common

