# training template for your executor app
# after build image, it should at /img-man/training-template.yaml
# key: gpu_id, task_id, pretrained_model_paths, class_names should be preserved

gpu_id: '0'
task_id: 'default-training-task'
pretrained_model_paths: []
class_names: []

# just for test, remove this key in your own docker image
expected_map: 0.983  # expected map for training task
idle_seconds: 60  # idle seconds for each task
