# training template for your executor app
# after build image, it should at /img-man/training-template.yaml
# key: gpu_id, task_id, pretrained_model_paths, class_names should be preserved

gpu_id: '0'
task_id: 'default-training-task'
pretrained_model_params: []
class_names: []

# format of annotations and images that ymir should provide to this docker container
#   annotation format: must be seg-coco
#   image format: must be raw
export_format: 'seg-coco:raw'

# just for test, remove this key in your own docker image
expected_mIoU: 0.983  # expected mIoU for training task
expected_mAcc: 0.800  # expected mAcc for training task
idle_seconds: 3  # idle seconds for each task
crash_code: 0  # 0, or 18xxxx(see also: code.py), generate an error message with this id if set non-zero value
