"""update user table

Revision ID: 98423cdb01df
Revises: aa709a1d876a
Create Date: 2021-11-24 11:24:48.442761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98423cdb01df'
down_revision = 'aa709a1d876a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
