import { createFromIconfontCN } from '@ant-design/icons'
import iconUrl from '@/assets/icons/iconfont'
import s from './common.less'

const IconFont = createFromIconfontCN({
  scriptUrl: iconUrl,
})

const iconFont = type => props => <IconFont type={`icon-${type}`} {...props} className={`${props.className || ''} ${s.cicon}`} />

export default iconFont

export const AddDelTwoIcon = iconFont('add-del-two')
export const ArrowDownIcon = iconFont('arrow-down')
export const AddTwoIcon = iconFont('add-two')
export const AddtaskIcon = iconFont('addtask')
export const ArrowRightIcon = iconFont('arrow-right')
export const AddIcon = iconFont('add')
export const EditIcon = iconFont('edit')
export const BookIcon = iconFont('book')
export const DeleteIcon = iconFont('delete')
export const FileHistoryIcon = iconFont('file-history')
export const BarchartIcon = iconFont('barchart')
export const EyeOnIcon = iconFont('eye-on')
export const FileYesIcon = iconFont('file-yes')
export const EnglishIcon = iconFont('english')
export const FailIcon = iconFont('fail')
export const EyeOffIcon = iconFont('eye-off')
export const ChinaIcon = iconFont('china')
export const FlowIcon = iconFont('flow')
export const ExcavateIcon = iconFont('excavate')
export const JiedianIcon = iconFont('jiedian')
export const MetadatasetIcon = iconFont('metadataset')
export const InprogressIcon = iconFont('inprogress')
export const MoreIcon = iconFont('more')
export const ImportIcon = iconFont('import')
export const ImageIcon = iconFont('image')
export const More1Icon = iconFont('more-1')
export const ManageIcon = iconFont('manage')
export const MymodelIcon = iconFont('mymodel')
export const NoIcon = iconFont('no')
export const NavHomeIcon = iconFont('nav-home')
export const NavDatasetIcon = iconFont('nav-dataset')
export const MydatasetIcon = iconFont('mydataset')
export const ProhibitIcon = iconFont('prohibit')
export const SoundIcon = iconFont('sound')
export const SearchIcon = iconFont('search')
export const RefreshIcon = iconFont('refresh')
export const ScreenIcon = iconFont('screen')
export const MytaskIcon = iconFont('mytask')
export const SearchEyeIcon = iconFont('search-eye')
export const NavTaskIcon = iconFont('nav-task')
export const NoXlmxIcon = iconFont('no-xlmx')
export const NavModelmanageIcon = iconFont('nav-modelmanage')
export const TipsIcon = iconFont('tips')
export const YesIcon = iconFont('yes')
export const OptimalModelIcon = iconFont('optimal-model')
export const TrainIcon = iconFont('train')
export const TrainsIcon = iconFont('trains')
export const TreeIcon = iconFont('tree')
export const UploadfileIcon = iconFont('uploadfile')
export const NoSjjIcon = iconFont('no-sjj')
export const SuccessIcon = iconFont('success')
export const ShieldIcon = iconFont('shield')
export const WajueIcon = iconFont('wajue')
export const TaggingIcon = iconFont('tagging')
export const ShutIcon = iconFont('shut-down')
export const LockIcon = iconFont('lock')
export const UserIcon = iconFont('user')
export const LogoutIcon = iconFont('logout')
export const EmailIcon = iconFont('email')
export const CopyIcon = iconFont('copy')
export const KeyIcon = iconFont('key')
export const SmartphoneIcon = iconFont('smartphone')
export const VectorIcon = iconFont('Vector')
export const FlagIcon = iconFont('flag')
export const PriceTagIcon = iconFont('price-tag')
export const PutawayIcon = iconFont('putaway')
export const DowntitleIcon = iconFont('downtitle')
export const CloseTwoIcon = iconFont('close-two')
export const StopIcon = iconFont('stop')
export const OpenTwoIcon = iconFont('open-two')
export const FileDownloadIcon = iconFont('file-download')
export const RecreateIcon = iconFont('recreate')
export const EqualizerIcon = iconFont('equalizer')
export const GithubIcon = iconFont('github')
export const ArrowUpIcon = iconFont('arrow-up')
export const FunnelIcon = iconFont('funnel')
export const UserSettingsIcon = iconFont('user-settings')
export const ReasoningIcon = iconFont('reasoning')
export const ClearIcon = iconFont('clear')
export const QuoteNubIcon = iconFont('quote-nub')
export const StaIcon = iconFont('sta')
export const StarHalfIcon = iconFont('star-half')
export const ShareIcon = iconFont('share')
export const UserSharedIcon = iconFont('user-shared')
export const LinkIcon = iconFont('user-associated')
export const TvIcon = iconFont('tv')
export const IterativeIcon = iconFont('Iterative')
export const BarChart2LineIcon = iconFont('bar-chart-2-line')
export const Artboard2LineIcon = iconFont('artboard-2-line')
export const Repeat2LineIcon = iconFont('repeat-2-line')
export const SkipBackMiniLineIcon = iconFont('skip-back-mini-line')
export const TerminalBoxLineIcon = iconFont('terminal-box-line')
export const BugLineIcon = iconFont('bug-line')
export const QuestionnaireLineIcon = iconFont('questionnaire-line')
export const BracketsLineIcon = iconFont('brackets-line')
export const GlobalLineIcon = iconFont('global-line')
export const ProjectIcon = iconFont('project')
export const RevertIcon = iconFont('revert')
export const CodeBoxLineIcon = iconFont('code-box-line')
export const LoaderIcon = iconFont('loader')
export const CompareListIcon = iconFont('than_list')
export const CompareIcon = iconFont('than')
export const PretreatmentIcon = iconFont('pretreatment')
