import { DatasetGroup, Dataset } from "@/interface/dataset"
import { Iteration } from './iteration'
export interface Project {
  id: number,
  name: string,
  type: number,
  keywords: Array<string>,
  candidateTrainSet: number,
  trainSet?: DatasetGroup,
  testSet?: Dataset,
  miningSet?: Dataset,
  testingSets?: Array<number>,
  setCount: number,
  trainSetVersion?: number,
  model?: number,
  modelStage?: Array<number>,
  modelCount: number,
  miningStrategy: number,
  chunkSize?: number,
  currentIteration?: Iteration,
  round: number,
  currentStage: number,
  createTime: string,
  updateTime: string,
  description?: string,
  isExample?: boolean,
  hiddenDatasets: Array<number>,
  hiddenModels: Array<number>,
  enableIteration: boolean,
  totalAssetCount: number,
  runningTaskCount: number,
  totalTaskCount: number,
}
