import { DatasetGroup, Dataset } from "@/interface/dataset"
type DatasetId = number
export interface Project {
  id: number,
  name: string,
  type: number,
  keywords: Array<string>,
  targetMap: number,
  targetDataset: number,
  targetInteration: number,
  trainSet?: DatasetGroup,
  testSet?: Dataset,
  miningSet?: Dataset,
  setCount: number,
  modelCount: number,
  miningStrategy: number,
  chunkSize?: number,
  currentInteration?: originInteration,
  createTime: string,
  updateTime: string,
  description?: string,
}

export interface Interation {
  id: number,
  name: string,
  version: number,
  currentStep: number,
  trainSet?: DatasetId,
  trainUpdateSet: DatasetId,
  miningSet?: DatasetId,
  miningResult?: DatasetId,
  labelSet?: DatasetId,
  model?: number,
}
export interface originInteration {
  id: number,
  name: string,
  version: number,
  current_step: number,
  iteration_round: number,
  train_set: DatasetId,
  train_update_result: DatasetId,
  mining_set?: DatasetId,
  mining_result?: DatasetId,
  label_set?: DatasetId,
  model?: number,
}

export interface originProject {
  id: number,
  name: string,
  training_keywords: Array<string>,
  train_set: Dataset,
  test_set: Dataset,
  mining_set: Dataset,
  dataset_count: number,
  model_count: number,
  mining_strategy: number,
  chunk_size: number,
  current_interation?: originInteration,
  create_datetime: string,
  update_datetime: string,
  description: string 
  training_type: number,
  iteration_target: number,
  map_target: number,
  training_dataset_count_target: number,
  current_iteration_id: number,
}
