"""update model: make parameters Text

Revision ID: faf55734ec0d
Revises: c3c42bab66c6
Create Date: 2022-01-27 11:32:36.626381

"""
import sqlalchemy as sa

from alembic import context, op

# revision identifiers, used by Alembic.
revision = "faf55734ec0d"
down_revision = "c3c42bab66c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if context.get_x_argument(as_dictionary=True).get("sqlite", None):
        with op.batch_alter_table("model") as batch_op:
            batch_op.alter_column(
                "parameters",
                existing_type=sa.VARCHAR(length=500),
                type_=sa.Text(length=500),
                existing_nullable=True,
            )
    else:
        op.alter_column(
            "model",
            "parameters",
            existing_type=sa.VARCHAR(length=500),
            type_=sa.Text(length=500),
            existing_nullable=True,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if context.get_x_argument(as_dictionary=True).get("sqlite", None):
        with op.batch_alter_table("model") as batch_op:
            batch_op.alter_column(
                "parameters",
                existing_type=sa.Text(length=500),
                type_=sa.VARCHAR(length=500),
                existing_nullable=True,
            )
    else:
        op.alter_column(
            "model",
            "parameters",
            existing_type=sa.Text(length=500),
            type_=sa.VARCHAR(length=500),
            existing_nullable=True,
        )
    # ### end Alembic commands ###
