name: viewer-unittest

on:
  pull_request:
    branches:
      - master
      - dev
      - ymir-pa

jobs:
  viewer-ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Verify dependencies
      working-directory: ymir/backend/src/ymir_viewer
      run: |
        go mod verify
        go build -v ./...
        go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Cache Go Environment
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: v1.48

        # Optional: working directory, useful for monorepos
        working-directory: ymir/backend/src/ymir_viewer

    - name: Lint and test code
      working-directory: ymir/backend/src/ymir_viewer
      run: |
        go vet ./...
        staticcheck ./...
        go test -race -cover -vet=off ./...
